version: "3.7"

services:
  api-portfolio-dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    env_file:
      - .env.development.local
    environment:
      - NODE_ENV=development.local
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  api-portfolio-prod:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    environment:
      - NODE_ENV=production.local
    ports:
      - "3000:3000"
    command: node dist/main
