version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Iniciando el daemon de Docker...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - echo Esperando a que Docker se inicie...
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Iniciando sesión en Amazon ECR...
      - aws --version
      - echo Región $AWS_REGION
      - echo Obteniendo URI del repositorio...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Obteniendo hash del commit...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Generando etiqueta de imagen...
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Compilación iniciada el `date`
      - echo Construyendo la imagen Docker...
      - docker build -t $REPOSITORY_URI:latest -f .docker/Dockerfile.prod .
      - echo Etiquetando la imagen Docker...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Compilación completada el `date`
      - echo Empujando las imágenes Docker...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Escribiendo el archivo de definiciones de imagen...
      - printf '[{"name":"portfolio-code-pipeline","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json