FROM node:18

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Set environment variables for development
ENV NODE_ENV=development

# Start the application in development mode
CMD ["npm", "run", "start:dev"]